"""add unidade e quantidade_minima em produto

Revision ID: 7a2d34e0c17a
Revises: e0cdb5939a05
Create Date: 2025-06-16 16:44:33.529931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2d34e0c17a'
down_revision = 'e0cdb5939a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade', sa.String(length=10), nullable=False, server_default='un'))
        batch_op.add_column(sa.Column('quantidade_minima', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('quantidade_minima')
        batch_op.drop_column('unidade')

    # ### end Alembic commands ###
